#!/bin/bash

use_java() {
  if [ "$#" -ne 1 ]; then
    echo "usage: use java VERSION" >&2
    return 1
  fi
  export JAVA_HOME="$(/usr/libexec/java_home -v "$1")"
  PATH_add $JAVA_HOME/bin
}

use_ruby() {
  if [ "$#" -ne 1 ]; then
    echo "usage: use ruby VERSION" >&2
    return 1
  fi
  load_prefix $HOME/.rubies/$1
  layout ruby
}

export_function() {
  local name=$1
  local alias_dir=$PWD/.direnv/aliases
  mkdir -p "$alias_dir"
  PATH_add "$alias_dir"
  local target="$alias_dir/$name"
  if declare -f "$name" >/dev/null; then
    echo "#!$SHELL" > "$target"
    declare -f "$name" >> "$target" 2>/dev/null
    echo "$name \$*" >> "$target"
    chmod +x "$target"
  fi
}
