[settings]
trusted_config_paths = [
  "~/in/github.com/yubrot",
]

[settings.ruby]
compile = false

[settings.github]
use_git_credentials = true

[tools]
go = "latest"
ruby = "latest"
node = "latest"
deno = "latest"
bun = "latest"
terraform = "latest"
